### ISSUE TITLE
configure failing with syntax error near unexpected token `11,,mandatory'

### ISSUE THREAD

**Issue by amanpsbhatia** [stormspirit/libtachyon#3]
Hi,

I was trying to setup the lib and followed the steps mentioned in the README.
The Configure step was failing with the following error :
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.3.0 dyld
checking how to hardcode library paths into programs... immediate
**../configure: line 16053: syntax error near unexpected token `11,,mandatory'
../configure: line 16053: `AX_CXX_COMPILE_STDCXX(11,,mandatory)'**

I am setting this up on OSX 10.11.3.

Thanks in advance.

**Comment by ryanphuang** [comment]
Hi @amanpsbhatia, 

This is due to a missing m4 macro used in `configure.ac` for checking C++ 11 support. I've checked in the macro in commit  ef7302f. Please update your repo and let me know if it resolves your issue.

**Comment by amanpsbhatia** [comment]
Hi,

Thanks. It worked.
