### ISSUE TITLE
Error Running Test

### ISSUE THREAD

**Issue by gupta-nikita** [stormspirit/libtachyon#5]
Hi

When I run the test using src/alluxiotest localhost 19998

I am getting the following error. Not sure why.
 src/alluxiotest localhost 19998
log4j:WARN No appenders could be found for logger (alluxio.logger.type).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

TEST - CREATE FILE: SUCCESS - Created alluxio file: /hello.txt

TEST - DELETE FILE: SUCCESS - Deleted path /hello.txt

Message: Native exception
From Java: java.io.FileNotFoundException: /home/nikks/alluxio/underFSStorage/hello.txt.alluxio.0x0A6B31B72329FA9F.tmp (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
	at alluxio.underfs.local.LocalUnderFileSystem.create(LocalUnderFileSystem.java:77)
	at alluxio.client.file.FileOutStream.<init>(FileOutStream.java:124)
	at alluxio.client.file.BaseFileSystem.createFile(BaseFileSystem.java:102)
TEST - CREATE FILE WITH OPTIONS: 

I haven't changed any of the configurations.

**Comment by ryanphuang** [comment]
Please refer to the guide in Alluxio: http://www.alluxio.org/docs/master/en/Getting-Started.html.
`underFSStorage` is the default path for the UnderFileSystem (UFS) in Alluxio. By default, it does not exist. You need to create it or call command like `./bin/alluxio fs persist /LICENSE`, which will create the path.
